[package]
name = "execut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.4"
axum-extra = { version = "0.9.2", features = ["typed-header"] }
chrono = { version = "0.4.35", features = ["serde"] }
csv = "1.3.0"
dotenvy = "0.15.7"
jsonwebtoken = "9.2.0"
once_cell = "1.19.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sqlx = { version = "0.7.3", features = ["chrono", "macros", "migrate", "postgres", "runtime-tokio", "uuid"] }
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = { version = "1.7.0", features = ["v7", "serde"] }
validators = "0.25.3"
