version: "3.9"

services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432

    volumes:
      - database:/var/lib/postgresql/data

    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: execut
      POSTGRES_DB: canary

volumes:
  database:
    driver: local
